data AMA_grad;
 Uni_ID=90010101;
 First_Name='Peter';
 Last_Name='Smith';
 Gender='M';
 GradYr=08;
 Output;
 Uni_ID=89241253;
 First_Name='Zhian';
 Last_Name='Yang';
 Gender='M';
 GradYr=11;
 Output;
 Uni_ID=91021201;
 First_Name='Chi Wah';
 Last_Name='Chan';
 Gender='F';
 GradYr=95;
 Output;
 Uni_ID=07012345;
 First_Name='Amy';
 Last_Name='Yip';
 Gender='F';
 GradYr=11;
 Output;
 Uni_ID=86012345;
 First_Name='Rose';
 Last_Name='Yip';
 Gender='F';
 GradYr=89;
 Output;
run;
proc print data=AMA_grad(Firstobs=2 Obs=4);
format Uni_ID Z8.0 GradYr Z4.0;
run;
proc print data = AMA_grad;
run;
/* When the output is missing, the corresponding data will not be stored in the data step assigned */
data AMA_grad_NO;
 Uni_ID=90010101;
 First_Name='Peter';
 Last_Name='Smith';
 Gender='M';
 GradYr=08;
 Output;
 Uni_ID=89241253;
 First_Name='Zhian';
 Last_Name='Yang';
 Gender='M';
 GradYr=11;
 Uni_ID=91021201;
 First_Name='Chi Wah';
 Last_Name='Chan';
 Gender='F';
 GradYr=95;
 Output;
 Uni_ID=07012345;
 First_Name='Amy';
 Last_Name='Yip';
 Gender='F';
 GradYr=11;
 Uni_ID=86012345;
 First_Name='Rose';
 Last_Name='Yip';
 Gender='F';
 GradYr=89;
 Output;
run;
Proc print data = AMA_grad_NO;
run;
data AMA_grad;
  length Uni_ID $8 First_Name $10 Last_Name $10 Gender $1 GradYr 8;
  Uni_ID='90010101'; First_Name='Peter';   Last_Name='Smith'; Gender='M'; GradYr=8;  output;
  Uni_ID='89241253'; First_Name='Zhian';   Last_Name='Yang';  Gender='M'; GradYr=11; output;
  Uni_ID='91021201'; First_Name='Chi Wah'; Last_Name='Chan';  Gender='F'; GradYr=95; output;
  Uni_ID='07012345'; First_Name='Amy';     Last_Name='Yip';   Gender='F'; GradYr=11; output;
  Uni_ID='86012345'; First_Name='Rose';    Last_Name='Yip';   Gender='F'; GradYr=89; output;
run;
proc print data=AMA_grad;
run;
data New;
set AMA_grad(OBS=4);
run;
proc print data = New;
run;


