data AMA_grad;
  length Uni_ID $8 First_Name $10 Last_Name $10 Gender $1 GradYr 8;
  Uni_ID='90010101'; First_Name='Peter';   Last_Name='Smith'; Gender='M'; GradYr=8;  output;
  Uni_ID='89241253'; First_Name='Zhian';   Last_Name='Yang';  Gender='M'; GradYr=11; output;
  Uni_ID='91021201'; First_Name='Chi Wah'; Last_Name='Chan';  Gender='F'; GradYr=95; output;
  Uni_ID='07012345'; First_Name='Amy';     Last_Name='Yip';   Gender='F'; GradYr=11; output;
  Uni_ID='86012345'; First_Name='Rose';    Last_Name='Yip';   Gender='F'; GradYr=89; output;
run;
Data grad95 grad08 grad11 grad_others;
set work.AMA_grad;
select(GradYr);
when (95) output grad95;
when (08) output grad08;
when (11) output grad11;
otherwise output grad_others;
end;
run;
proc print data = grad95;
run;
proc print data = grad08;
run;
proc print data = grad11;
run;
proc print data = grad_others;
run;
/* Another way of select function */
Data grad95 grad08 grad11 grad_others;
set work.AMA_grad;
select;
when (GradYr = 95) output grad95;
when (GradYr = 08) output grad08;
when (GradYr = 11) output grad11;
otherwise output grad_others;
end;
run;
proc print data = grad95;
run;
proc print data = grad08;
run;
proc print data = grad11;
run;
proc print data = grad_others;
run;

