libname xlsdata "D:\SAS_Datasets\PolyU_overseas_staff.xlsx";
proc summary data=xlsdata."polyu_overseas_staff$"n;
var salary;
class gender origin_country;
output out=output_summary;
run;
proc print data=output_summary;
run;
title " ";
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class origin_country;
table origin_country;
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class gender origin_country;
table gender, origin_country;
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class rank gender origin_country;
table rank, gender, origin_country;
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class origin_country;
var salary;
table origin_country*salary*(min mean max);
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class gender origin_country;
var salary;
table gender all, origin_country*salary;
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class origin_country;
var salary;
table origin_country*salary*(N min mean max);
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n;
class origin_country gender;
var salary;
table gender all, origin_country*salary*(N min mean max);
run;
proc tabulate data=xlsdata."polyu_overseas_staff$"n out=work.tabulate;
class rank gender origin_country;
table gender;
table origin_country;
table rank, gender, origin_country;
run;
proc print data=work.tabulate;
run;
